site_name: CDS Hooks

theme:
  name: 'material'
  logo: 'images/logo-square.png'
  favicon: 'images/favicon.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/cds-hooks'

nav:
- Overview: 'index.md'
- Specification:
    - '1.0': 'specification/1.0.md'
- Hooks:
    - 'new-hook-template' : 'hooks/template.md'
    - allergyintolerance-create : 'hooks/allergyintolerance-create.md'
    - 'patient-view' : 'hooks/patient-view.md'
    - 'medication-prescribe' : 'hooks/medication-prescribe.md'
    - 'order-review' : 'hooks/order-review.md'
- Quick Start: 'quickstart.md'
- Examples: 'examples.md'
- Community: 'community.md'

repo_url: 'https://github.com/cds-hooks/docs'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true

copyright: Â© 2018 HL7 & Boston Children's Hospital.<p /> <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
