site_name: CDS Hooks

theme:
  name: 'material'
  logo: 'images/logo-square.png'
  favicon: 'images/favicon.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/cds-hooks'

nav:
- Overview: 'index.md'
- Specification:
    - '1.0': 'specification/1.0.md'
- Hooks:
    - 'new-hook-template' : 'hooks/template.md'
    - 'patient-view 4' : 'hooks/patient-view.md'
    - 'medication-prescribe 2' : 'hooks/medication-prescribe.md'
    - 'order-review 3' : 'hooks/order-review.md'
    - 'order-select 1' : 'hooks/order-select.md'
    - 'order-sign 1' : 'hooks/order-sign.md'
    - 'appointment-book 1' : 'hooks/appointment-book.md'
    - 'encounter-start 1' : 'hooks/encounter-start.md'
    - 'encounter-discharge 1' : 'hooks/encounter-discharge.md'
- Quick Start: 'quickstart.md'
- Cheat Sheet: 'cheat-sheet/Cheat Sheet - Sept 2019.pdf'
- Best Practices: 'best-practices.md'
- Examples: 'examples.md'
- Community: 'community.md'
- Logo Use: 'logo-use.md'

repo_url: 'https://github.com/cds-hooks/docs'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true

copyright: Â© 2018 HL7 & Boston Children's Hospital.<p /> <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
